### PR TITLE
Blackened

### PR DESCRIPTION
**Pull request by rayluo**

### CODE REVIEW

**Comment by davidism** [comment]
Address other PRs before merging style changes like this, as this will make it impossible to merge all of them. In particular, get #170 first.

**Comment by rayluo** [comment]
> In particular, get #170 first.

This is actually a subset of the 1500-lines #170. If/when we merge in this one (and possible after rebasing #170), #170 will become smaller to review. I am trying to divide and conquer #170, by splitting it into several atomic PRs.

> Address other PRs before merging style changes like this, as this will make it impossible to merge all of them.

In particular, other PRs will be "impossible to merge" too, after we merge in #170, because #170 unfortunately has those style changes baked in. If you really want us to still potentially review and merge in other old PRs, then we shall NOT merge in #170 as-is. I have no problem abandoning this styling draft, and I can proceed to divide other functional changes of #170 into smaller PRs.

**Comment by davidism** [comment]
Sorry, I didn't realize all that, go ahead with whatever you feel is best, I just chimed in from the sidelines.

**Comment by ThiefMaster** [comment]
ah damn noticed this one too late: the main pallets repos recently moved to ruff which is a drop-in replacement for black, flake8, etc - but unlike black it let's you prefer with single quotes (not used in pallets atm though) which would have likely kept the diff quite a bit shorter...

**Pull request merged**
