### PR TITLE
Replaced deprecated app.session_cookie_name with app.config["SESSION_COOKIE_NAME"].

### PR DESCRIPTION
**Pull request by imacat**

### CODE REVIEW

**Review by eladavron — APPROVED** [review]

**Review by rayluo — APPROVED** [review]
This PR looks adequately changed all occurrences of `session_cookie_name` to the new approach in Flask 2.3+, thus shall be able to fix #150.

Before release, the [setup.py file shall ideally also be changed](https://github.com/fengsp/flask-session/blob/master/setup.py#L32) to declare "flask>=2.2".

@fengsp , do you plan to merge it in and cut a release soon?
If you would assign me the `Write` permission to this repo, I will happily help the merge and release. FYI, currently, [one of my projects](https://github.com/Azure-Samples/ms-identity-python-webapp) uses `flask-session` as a dependency, so I have an interest here to improve `flask-session`, too.

**Comment by fengsp** [comment]
@rayluo It seems this breaks for anyone who is using Flask < 2.3 ?

**Comment by rayluo** [comment]
Welcome back, @fengsp ! 

> @rayluo It seems this breaks for anyone who is using Flask < 2.3 ?

Not necessarily. Flask-session itself uses semantic versioning. We can have flask-session 0.4.x contain working with Flask < 2.3, and have flask-session 0.5+ using Flask >= 2.2.

**Comment by imacat** [comment]
> @rayluo It seems this breaks for anyone who is using Flask < 2.3 ?

I do not think this is an issue.  When we have:

* Flask-Session 0.4.x: install_requires: Flask >=0.8, <2.3
* Flask-Session 0.5.0: install_requires: Flask >=2.2

People running Flask<2.3 can still use Flask-Session==0.4.x nicely.

**Comment by davidism** [comment]
Flask-Session 0.5.0 is now available.

**Pull request merged**
