### PR TITLE
pymongo v4 support

### PR DESCRIPTION
**Pull request by ItsCh1ya**
pymongo 4.0 required operators in update func

### CODE REVIEW

**Comment by vivCoding** [comment]
Line 444 on the same file might also need a fix, from `self.store.remove` to `self.store.delete_one`

**Comment by jakefischer** [comment]
These updates make pymongo <4.0 no longer compatible. The fix should probably have a version check.

**Comment by heyiamzach** [comment]
I have completely fixed both feng's flask-session and itsch1ya's flask-session
 
 here is a completely fixed version: https://github.com/heyiamzach/flask-session
 
 I've made a pull request here: https://github.com/fengsp/flask-session/pull/154

**Comment by Lxstr** [comment]
This is now supported in latest version

**Pull request closed without merging**
